### ISSUE TITLE
Why wait to set "new TronWeb()" to window.tronWeb for 1 second?

### ISSUE THREAD

**Issue by yanmagithub** [TronWatch/TronLink-Demo-Messages#8]
In componentDidMount() of "App" component, "new TronWeb()" is set to window.tronWeb after max 1 second (100ms x 10) if a user does not have TronLink.
Here:
https://github.com/TronWatch/TronLink-Demo-Messages/blob/094df9b5890b5523c3f423be231d170bbcf4f572/src/components/App/index.js#L60

I would like to know what reason does the 1 second come from because the following sample code sets immediately on load.
https://developers.tron.network/docs/wallet-integration

I feel bad for wasting your time with a basic question, but could you tell me why?
Thanks.

**Comment by tayler-king** [comment]
Chrome doesn't always execute it immediately, sometimes it can take a few ms. It's highly unlikely to ever take 1s, but probably possible on slow connections which is why we wait 1 second maximum.

**Comment by yanmagithub** [comment]
Thank you for the kind and detailed reply! It's very helpful for us.

**Comment by tayler-king** [comment]
You're welcome :)
